<?php

namespace Proxies\__CG__\Otros\TareaOperativaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TareaOperativa extends \Otros\TareaOperativaBundle\Entity\TareaOperativa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'id', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'fechaCreacion', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'descripcion', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'numero', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'estadoTareaOperativa', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'tareaOperativaTrabajador', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'accionTareaOperativa', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'chequeoTareaOperativa');
        }

        return array('__isInitialized__', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'id', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'fechaCreacion', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'descripcion', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'numero', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'estadoTareaOperativa', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'tareaOperativaTrabajador', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'accionTareaOperativa', '' . "\0" . 'Otros\\TareaOperativaBundle\\Entity\\TareaOperativa' . "\0" . 'chequeoTareaOperativa');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TareaOperativa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function addEstadoTareaOperativa(\Otros\TareaOperativaBundle\Entity\EstadoTareaOperativa $estadoTareaOperativa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEstadoTareaOperativa', array($estadoTareaOperativa));

        return parent::addEstadoTareaOperativa($estadoTareaOperativa);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEstadoTareaOperativa(\Otros\TareaOperativaBundle\Entity\EstadoTareaOperativa $estadoTareaOperativa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEstadoTareaOperativa', array($estadoTareaOperativa));

        return parent::removeEstadoTareaOperativa($estadoTareaOperativa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoTareaOperativa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoTareaOperativa', array());

        return parent::getEstadoTareaOperativa();
    }

    /**
     * {@inheritDoc}
     */
    public function addTareaOperativaTrabajador(\Otros\TareaOperativaBundle\Entity\TareaOperativaTrabajador $tareaOperativaTrabajador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTareaOperativaTrabajador', array($tareaOperativaTrabajador));

        return parent::addTareaOperativaTrabajador($tareaOperativaTrabajador);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTareaOperativaTrabajador(\Otros\TareaOperativaBundle\Entity\TareaOperativaTrabajador $tareaOperativaTrabajador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTareaOperativaTrabajador', array($tareaOperativaTrabajador));

        return parent::removeTareaOperativaTrabajador($tareaOperativaTrabajador);
    }

    /**
     * {@inheritDoc}
     */
    public function getTareaOperativaTrabajador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTareaOperativaTrabajador', array());

        return parent::getTareaOperativaTrabajador();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastEstadoTareaOperativa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastEstadoTareaOperativa', array());

        return parent::getLastEstadoTareaOperativa();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFinal', array());

        return parent::getFechaFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function addAccionTareaOperativa(\Otros\TareaOperativaBundle\Entity\AccionTareaOperativa $accionTareaOperativa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAccionTareaOperativa', array($accionTareaOperativa));

        return parent::addAccionTareaOperativa($accionTareaOperativa);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccionTareaOperativa(\Otros\TareaOperativaBundle\Entity\AccionTareaOperativa $accionTareaOperativa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccionTareaOperativa', array($accionTareaOperativa));

        return parent::removeAccionTareaOperativa($accionTareaOperativa);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccionTareaOperativa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccionTareaOperativa', array());

        return parent::getAccionTareaOperativa();
    }

    /**
     * {@inheritDoc}
     */
    public function addChequeoTareaOperativa(\Otros\TareaOperativaBundle\Entity\ChequeoTareaOperativa $chequeoTareaOperativa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChequeoTareaOperativa', array($chequeoTareaOperativa));

        return parent::addChequeoTareaOperativa($chequeoTareaOperativa);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChequeoTareaOperativa(\Otros\TareaOperativaBundle\Entity\ChequeoTareaOperativa $chequeoTareaOperativa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChequeoTareaOperativa', array($chequeoTareaOperativa));

        return parent::removeChequeoTareaOperativa($chequeoTareaOperativa);
    }

    /**
     * {@inheritDoc}
     */
    public function getChequeoTareaOperativa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChequeoTareaOperativa', array());

        return parent::getChequeoTareaOperativa();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($val));

        return parent::toArray($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaResponsableAndTrabajadorId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaResponsableAndTrabajadorId', array());

        return parent::getAreaResponsableAndTrabajadorId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroTarea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroTarea', array());

        return parent::getNumeroTarea();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataChartBar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataChartBar', array());

        return parent::getDataChartBar();
    }

}
