<?php

namespace Proxies\__CG__\Otros\NomencladorBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Trabajador extends \Otros\NomencladorBundle\Entity\Trabajador implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'id', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'numeroPlaza', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'nombreApellidos', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'movil', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'area', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'cargo', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'departamento');
        }

        return array('__isInitialized__', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'id', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'numeroPlaza', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'nombreApellidos', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'movil', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'area', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'cargo', '' . "\0" . 'Otros\\NomencladorBundle\\Entity\\Trabajador' . "\0" . 'departamento');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Trabajador $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroPlaza($numeroPlaza)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroPlaza', array($numeroPlaza));

        return parent::setNumeroPlaza($numeroPlaza);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroPlaza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroPlaza', array());

        return parent::getNumeroPlaza();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreApellidos($nombreApellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreApellidos', array($nombreApellidos));

        return parent::setNombreApellidos($nombreApellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreApellidos', array());

        return parent::getNombreApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setMovil($movil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMovil', array($movil));

        return parent::setMovil($movil);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovil', array());

        return parent::getMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea(\Otros\NomencladorBundle\Entity\Area $area = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', array($area));

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', array());

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargo(\Otros\NomencladorBundle\Entity\Cargo $cargo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargo', array($cargo));

        return parent::setCargo($cargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargo', array());

        return parent::getCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartamento(\Otros\NomencladorBundle\Entity\Departamento $departamento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartamento', array($departamento));

        return parent::setDepartamento($departamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartamento', array());

        return parent::getDepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
