#Administrador#
admin: [ ROLE_ADMIN ]

#App Transporte#
indicadores: [ ROLE_INDICADOR, ROLE_EDITOR_INDICADOR ]

#App Transporte#
transporte: [ ROLE_TRANSPORTE, ROLE_PLANIFICADOR_TRANSPORTE, ROLE_ESPECIALISTA_TRANSPORTE, ROLE_SUPERVISOR_TRANSPORTE, ROLE_TECNICO_TRANSPORTE ]

#TAREAS OPERATIVAAS#
tareas_operativas: [ ROLE_TAREASOPERATIVAS, ROLE_SUPERVISOR_TAREAS_OPERATIVAS, ROLE_ESPECIALISTA_TAREAS_OPERATIVAS, ROLE_TECNICO_TAREAS_OPERATIVAS, ROLE_RESPONSABLE_TAREAS_OPERATIVAS ]

#CONTROL CALIDAD#
control_calidad: [ ROLE_CONTROLCALIDAD, ROLE_ESPECIALISTA_CONTROL_CALIDAD, ROLE_RESPONSABLE_CONTROL_CALIDAD ]