#Otros\NomencladorBundle\Entity\Cargo:
#    constraints:
#        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nombre
#        
#Otros\NomencladorBundle\Entity\Departamento:
#    constraints:
#        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nombre
#        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: acronimo
#        
#Otros\NomencladorBundle\Entity\Trabajador:
#    constraints:
#        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: ci
#        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [nombre, apellidos]