## ETECSA UNIDADES ORGANIZATIVAS ##
VPP: Vicepresidencia Primera
#DESP: Despacho
#DRIN: Dirección de Relaciones Internacionales
#DICR: Dirección de Cuadro
#DAUD: Dirección de Auditoría
#DIAL: Dirección de Asuntos Legales
#CDNT: Centro de Dirección Nacional de Telecomunicaciones
#DECA: Dirección Económico Administrativa
#DINE: Dirección de Inteligencia Empresarial
#DOPS: Dirección de Operaciones de Seguridad
#DVTN: División de Talleres Nacionales
DCDT: Dirección Central de Desarrollo y Terminología
DCCM: Dirección Central de Comercial y Mercadotecnia
DCNI: Dirección Central de Negociación e Importaciones
DCCH: Dirección Central de Capital Humano
DCEC: Dirección Central de Economía
DCSD: Dirección Central de Control, Seguridad y Defensa
DVSM: División de Servicios Móviles
DVSF: División de Servicios Fijos
DVTP: División de Servicios de Telefonía Pública
DVSI: División de Servicios Internacionales
DVTI: División de Tecnología de la Información
DVLS: División de Logística y Servicios
DVPE: División de Proyectos y Ejecución de Obras
DVLH: División La Habana
DTPR: División Territorial Pinar del Rio
DTAR: División Territorial Artemisa
DTMY: División Territorial Mayabeque
DTNO: División Territorial Norte
DTSP: División Territorial Sur
DTES: División Territorial Este
DTOE: División Territorial Oeste
DTMZ: División Territorial Matanzas
DTVC: División Territorial Villa Clara
DTCF: División Territorial Cienfuegos
DTSS: División Territorial Sancti Spiritus
DTCA: División Territorial Ciego de Ávila
DTCM: División Territorial Camaguey
DTLT: División Territorial Las Tunas
DTHO: División Territorial Holguín
DTGR: División Territorial Granma
DTSC: División Territorial Santiago de Cuba
DTGT: División Territorial Guantánamo
DTIJ: División Territorial Isla de la Juventud
## NO MODIFICAR ##